# --- Dependencies ---
FROM bitwalker/alpine-elixir-phoenix:1.10.3 AS deps
WORKDIR /app
COPY mix.exs mix.lock ./
RUN MIX_ENV=prod mix do deps.get --only prod, deps.compile

# --- Build ---
FROM bitwalker/alpine-elixir-phoenix:1.10.3 AS build

ENV IG_SERVICE_DB_USER=${IG_SERVICE_DB_USER}
ENV IG_SERVICE_DB_PASS=${IG_SERVICE_DB_PASS}
ENV IG_SERVICE_DB=${IG_SERVICE_DB}
ENV IG_SERVICE_DB_HOST=${IG_SERVICE_DB_HOST}
ENV IG_SERVICE_DB_POOL_SIZE=${IG_SERVICE_DB_POOL_SIZE}
ENV IG_SERVICE_SECRET_KEY_BASE=${IG_SERVICE_SECRET_KEY_BASE}
ENV IG_SERVICE_HOSTNAME=${IG_SERVICE_HOSTNAME}
ENV IG_SERVICE_PORT=${IG_SERVICE_PORT}
ENV IG_SERVICE_RUN_SCHEDULES=${IG_SERVICE_RUN_SCHEDULES}
ENV IG_SERVICE_TRENDS_SERVER_URL=${IG_SERVICE_TRENDS_SERVER_URL}
ENV IG_SERVICE_SELECTED_DATASOURCES=${IG_SERVICE_SELECTED_DATASOURCES}

WORKDIR /app
COPY . .
COPY --from=deps /app ./
RUN MIX_ENV=prod mix do phx.digest, release --overwrite

# --- Run ---
FROM alpine:latest
RUN apk update && apk --no-cache --update add bash openssl

ENV IG_SERVICE_DB_USER=${IG_SERVICE_DB_USER}
ENV IG_SERVICE_DB_PASS=${IG_SERVICE_DB_PASS}
ENV IG_SERVICE_DB=${IG_SERVICE_DB}
ENV IG_SERVICE_DB_HOST=${IG_SERVICE_DB_HOST}
ENV IG_SERVICE_DB_POOL_SIZE=${IG_SERVICE_DB_POOL_SIZE}
ENV IG_SERVICE_SECRET_KEY_BASE=${IG_SERVICE_SECRET_KEY_BASE}
ENV IG_SERVICE_HOSTNAME=${IG_SERVICE_HOSTNAME}
ENV IG_SERVICE_PORT=${IG_SERVICE_PORT}
ENV IG_SERVICE_RUN_SCHEDULES=${IG_SERVICE_RUN_SCHEDULES}
ENV IG_SERVICE_TRENDS_SERVER_URL=${IG_SERVICE_TRENDS_SERVER_URL}
ENV IG_SERVICE_SELECTED_DATASOURCES=${IG_SERVICE_SELECTED_DATASOURCES}

WORKDIR /app
COPY --from=build /app/_build/prod/rel/instagram_service .

CMD ["bin/expense_tracker", "start"]