apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: expense-tracker-secrets
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: expense-tracker-secrets
  data:
  - secretKey: dbPass
    remoteRef:
      key: secret/expense-tracker/db-pass
      property: value
  - secretKey: secretKeyBase
    remoteRef:
      key: secret/expense-tracker/secret-key-base
      property: value