apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: expense-tracker-secrets
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: expense-tracker-secrets
  data:
  - secretKey: dbPass
    remoteRef:
      key: secret/expense-tracker
      property: db_pass
  - secretKey: secretKeyBase
    remoteRef:
      key: secret/expense-tracker
      property: key_base